services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=gema
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gema

volumes:
  postgres_data:
